### CONFIG
@BASE_URL = http://127.0.0.1:8000/dominoapp/
@ADMIN_TOKEN = 11a4be82b49191741a7d19d219a3542555011209
@BUILDING_ID = 

### Wypisanie budynkow
GET {{BASE_URL}}buildings/
Authorization: Token {{ADMIN_TOKEN}}

###

### Admin: tworzymy budynek
POST {{BASE_URL}}buildings/
Authorization: Token {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "BuildingStreet": "Kwiatowa",
  "BuildingNumber": "15",
  "BuildingCity": "Warszawa",
  "BuildingPostal": "00-003"
}

###

### Sprawdzamy budynek
GET {{BASE_URL}}buildings/{{BUILDING_ID}}/
Authorization: Token {{ADMIN_TOKEN}}

###

### Admin: update budynku - PUT (powinnismy full update)
PUT {{BASE_URL}}buildings/{{BUILDING_ID}}/
Authorization: Token {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "BuildingStreet": "Kwiatowa",
  "BuildingNumber": "15B",
  "BuildingCity": "Warszawa",
  "BuildingPostal": "00-002"
}

###

### Admin: wywalenie budynku
DELETE {{BASE_URL}}buildings/{{BUILDING_ID}}/
Authorization: Token {{ADMIN_TOKEN}}
