# Generated by Django 5.2.8 on 2025-12-06 10:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('BuildingId', models.BigAutoField(primary_key=True, serialize=False)),
                ('BuildingStreet', models.CharField(max_length=30)),
                ('BuildingNumber', models.CharField(max_length=10)),
                ('BuildingCity', models.CharField(max_length=50)),
                ('BuildingPostal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.BigAutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=30)),
                ('UserSurname', models.CharField(max_length=40)),
                ('UserEmail', models.CharField(max_length=100)),
                ('UserPassword', models.CharField(max_length=40)),
                ('UserRole', models.CharField(choices=[('ADMIN', 'Administrator'), ('RESIDENT', 'Mieszkaniec')], max_length=10)),
                ('UserDate', models.DateField()),
                ('UserStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('FlatId', models.BigAutoField(primary_key=True, serialize=False)),
                ('FlatNumber', models.CharField(max_length=10)),
                ('FlatFloor', models.SmallIntegerField()),
                ('FlatArea', models.DecimalField(decimal_places=2, max_digits=6)),
                ('FlatStatus', models.BooleanField(default=True)),
                ('BuildingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='DominoApp.building')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('RentId', models.BigAutoField(primary_key=True, serialize=False)),
                ('RentMonth', models.SmallIntegerField()),
                ('RentYear', models.SmallIntegerField()),
                ('RentAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('RentDateDue', models.DateField()),
                ('RentStatus', models.CharField(choices=[('PAID', 'Zapłacone'), ('PENDING', 'Oczekujące')], default='PAID', max_length=10)),
                ('RentDate', models.DateField(blank=True, null=True)),
                ('FlatId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='DominoApp.flat')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('ReportId', models.BigAutoField(primary_key=True, serialize=False)),
                ('ReportType', models.CharField(choices=[('FLAT', 'Mieszkanie'), ('BUILDING', ' Budynek'), ('GENERAL', 'Ogólne')], default='GENERAL', max_length=10)),
                ('ReportTitle', models.CharField(max_length=100)),
                ('ReportDescription', models.TextField()),
                ('ReportCategory', models.CharField(max_length=500)),
                ('ReportStatus', models.CharField(choices=[('DONE', 'Wykonane'), ('ABANDONED', 'Porzucone'), ('WAITING', 'Oczekujące')], default='WAITING', max_length=15)),
                ('ReportTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('BuildingId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DominoApp.building')),
                ('FlatId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DominoApp.flat')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='DominoApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Announ',
            fields=[
                ('AnnounId', models.BigAutoField(primary_key=True, serialize=False)),
                ('AnnounTitle', models.CharField(max_length=100)),
                ('AnnounDescription', models.TextField()),
                ('AnnounDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('AnnounFrom', models.DateField()),
                ('AnnounTo', models.DateField(blank=True, null=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announs', to='DominoApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserFlat',
            fields=[
                ('UserFlatId', models.BigAutoField(primary_key=True, serialize=False)),
                ('UserFlatDateFrom', models.DateField(auto_now_add=True)),
                ('UserFlatDateTo', models.DateField(blank=True, null=True)),
                ('UserFlatRole', models.CharField(choices=[('OWNER', 'Właściciel'), ('TENANT', ' Najemca')], max_length=10)),
                ('FlatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userflats', to='DominoApp.flat')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userflats', to='DominoApp.user')),
            ],
            options={
                'unique_together': {('UserId', 'FlatId', 'UserFlatDateFrom')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='Flats',
            field=models.ManyToManyField(related_name='users', through='DominoApp.UserFlat', to='DominoApp.flat'),
        ),
    ]
