# Generated by Django 5.2.8 on 2025-12-06 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DominoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='FlatId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='DominoApp.flat'),
        ),
    ]
