# Generated by Django 6.0 on 2025-12-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DominoApp', '0002_alter_rent_flatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserEmail',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserPassword',
            field=models.CharField(max_length=128),
        ),
    ]
