# Generated by Django 6.0 on 2025-12-07 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DominoApp', '0003_alter_user_useremail_alter_user_userpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('TokenId', models.BigAutoField(primary_key=True, serialize=False)),
                ('TokenKey', models.CharField(max_length=40, unique=True)),
                ('TokenCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='DominoApp.user')),
            ],
        ),
    ]
