# Generated by Django 6.0 on 2025-12-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DominoApp', '0004_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='RentStatus',
            field=models.CharField(choices=[('PAID', 'Zapłacone'), ('PENDING', 'Oczekujące')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='ReportType',
            field=models.CharField(choices=[('FLAT', 'Mieszkanie'), ('BUILDING', 'Budynek'), ('GENERAL', 'Ogólne')], default='GENERAL', max_length=10),
        ),
    ]
