# Generated by Django 6.0 on 2025-12-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DominoApp', '0005_alter_rent_rentstatus_alter_report_reporttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
