# Generated by Django 5.2.8 on 2025-12-16 14:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DominoApp', '0006_alter_user_userdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='RentAmount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('BuildingStreet', 'BuildingNumber', 'BuildingCity', 'BuildingPostal')},
        ),
    ]
