### CONFIG
@BASE_URL = http://127.0.0.1:8000/dominoapp/
@ADMIN_TOKEN = 11a4be82b49191741a7d19d219a3542555011209
@RESIDENT_TOKEN = f9588e626501f47d37d8394720bb9179a626e6f8

### Tworzymy budynek
POST {{BASE_URL}}buildings/
Authorization: Token {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "BuildingStreet": "TestowaPierwsza",
  "BuildingNumber": "10A",
  "BuildingCity": "Warszawa",
  "BuildingPostal": "00-001"
}

### Tworzymy drugi budynek
POST {{BASE_URL}}buildings/
Authorization: Token {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "BuildingStreet": "TestowaDruga",
  "BuildingNumber": "10b",
  "BuildingCity": "Warszawa",
  "BuildingPostal": "00-002"
}

### Tworzymy mieszkanie w pierwszym budynku
# Wklej odpowiedni BUILDING_ID 
POST {{BASE_URL}}buildings/1/flats/
Authorization: Token {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "FlatNumber": "1",
  "FlatFloor": 1,
  "FlatArea": 50.5,
  "FlatStatus": true
}

### Tworzymy mieszkanie w drugim budynku
# Wklej odpowiedni BUILDING_ID 
POST {{BASE_URL}}buildings/2/flats/
Authorization: Token {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "FlatNumber": "1",
  "FlatFloor": 1,
  "FlatArea": 50.5,
  "FlatStatus": true
}

### Tworzymy BUILDING report dla tych dwoch budynkow, rezydent musi miec mieszkanie w tym budynku
POST {{BASE_URL}}my/reports/
Authorization: Token {{RESIDENT_TOKEN}}
Content-Type: application/json

{
  "ReportType": "BUILDING",
  "BuildingId": 2,
  "ReportTitle": "Problem w budynku",
  "ReportDescription": "Nie działa smietnik",
  "ReportCategory": "Techniczne"
}

### Wypisujemy zgloszenia dla poszczegolnych budynkow a konkretniej statystyke rozbita na statusy
GET {{BASE_URL}}reportstats/
Authorization: Token {{ADMIN_TOKEN}}

### Tutaj probujemy tego samego z tokenem rezydenta powinno byc 403
GET {{BASE_URL}}reportstats/
Authorization: Token {{RESIDENT_TOKEN}}
