### CONFIG
@BASE_URL = http://127.0.0.1:8000/dominoapp/
@ADMIN_TOKEN = c045d2dcab33f80c8d3d1679974e4756ef234166

### Tworzymy budynek
POST {{BASE_URL}}buildings/
Authorization: Token {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "BuildingStreet": "TestowaPierwsza",
  "BuildingNumber": "10A",
  "BuildingCity": "Warszawa",
  "BuildingPostal": "00-001"
}

### Tworzymy drugi budynek
POST {{BASE_URL}}buildings/
Authorization: Token {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "BuildingStreet": "TestowaDruga",
  "BuildingNumber": "10b",
  "BuildingCity": "Warszawa",
  "BuildingPostal": "00-002"
}

### Tworzymy mieszkanie w pierwszym budynku
# Wklej odpowiedni BUILDING_ID 
POST {{BASE_URL}}buildings/1/flats/
Authorization: Token {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "FlatNumber": "1",
  "FlatFloor": 1,
  "FlatArea": 50.5,
  "FlatStatus": true
}

### Tworzymy mieszkanie w drugim budynku
# Wklej odpowiedni BUILDING_ID 
POST {{BASE_URL}}buildings/2/flats/
Authorization: Token {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "FlatNumber": "1",
  "FlatFloor": 1,
  "FlatArea": 50.5,
  "FlatStatus": true
}

### Create BUILDING report
POST {{BASE_URL}}my/reports/
Authorization: Token {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "ReportType": "BUILDING",
  "BuildingId": {{BUILDING_ID}},
  "ReportTitle": "Problem w budynku",
  "ReportDescription": "Nie działa winda",
  "ReportCategory": "Techniczne"
}

### Wypisujemy zgłoszenia dla poszczególnych budynków
GET {{BASE_URL}}reportstats/
Authorization: Token {{ADMIN_TOKEN}}
